### ISSUE TITLE
Expand Scenario Outlines

### ISSUE THREAD

**Issue by ksmithbaylor** [Wallaceh/cukeforker#11]
My company uses CukeForker along with Selenium Grid for automation testing, and loves it!

Recently, we are having trouble running Cucumber Scenario Outlines in parallel. Currently, it seems that CukeForker treats the Outline as a single scenario instead of expanding it to multiple Scenarios so it can be split up across workers.

What is the best way to achieve this? The call we are using right now is this:

```ruby
   CukeForker::WebDriver::Runner.run(
       CukeForker::Scenarios.all,
       { :max => 10,
         :format => :json,
         :vnc => false,
         :extra_args => %W[-p parallel]
       })
```

**Comment by Wallaceh** [comment]
I just tested this, and if you are on cucumber 2+, scenario outlines are treated as individual scenarios now, not as a single scenario executed multiple times. 

If you update to latest, cukeforker will fork each example in an outline as an individual worker.
