### ISSUE TITLE
FeaturesLoader Class no longer exists

### ISSUE THREAD

**Issue by mglaze** [Wallaceh/cukeforker#14]
As of Cucumber 2.0.0, the required path `cucumber/runtime/features_loader` in `lib/cukeforker/scenarios.rb` no longer exists as a path. All feature loading is handled in `cucumber-ruby-core`.. [see article](https://github.com/cucumber/cucumber-ruby/issues/733#issuecomment-54790240). Are there any plans to update cukeforker to work with the latest version of cucumber? Or is there a work around for loading the feature files?

![image](https://cloud.githubusercontent.com/assets/1659393/13086731/7816830c-d4b2-11e5-8cff-09e2eeeaff1b.png)

**Comment by jarib** [comment]
I don't use cucumber much these days, but I can accept a pull request or transfer the repo to you if you'd like to maintain it.

**Comment by Wallaceh** [comment]
Hello there. I forked the project on Monday, and I believe I have it updated and working for cucumber 2.3.2. If you don't want to actively maintain it anymore, I'd love to have you transfer it.

**Comment by jarib** [comment]
Great that you want to take over maintenance! 

However, since there's already a repo at Wallaceh/cukeforker, I can't transfer the repo to you. Please delete or rename it and let me know.

I'll also need to know your rubygems.org email in order to make you a gem owner.

**Comment by Wallaceh** [comment]
I renamed the repo to wallaceh/cukeforker_temp, so it should be good to go now.

I'm on rubygems as wallaceh@gmail.com.

Thanks!

**Comment by jarib** [comment]
Looks like that didn't do the trick:

![image](https://cloud.githubusercontent.com/assets/572/13957868/480ab2a2-f04e-11e5-8631-c2f4a348f036.png)

Looks like you'll have to delete the GitHub repo completely.

**Comment by Wallaceh** [comment]
done too. Completely deleted

**Comment by jarib** [comment]
Transfer initiated and you're added as a gem owner. Thanks!

**Comment by Wallaceh** [comment]
thank you! Looking forward to keeping your gem going!

**Comment by Wallaceh** [comment]
fixed with version 1.0.0 release
